### ISSUE TITLE
Zip file does not unzip

### ISSUE THREAD

**Issue by elledgeg** [fritzing/fritzing-parts#109]
When attempting to unzip the zip file I get the messge:
socrates:Downloads gjwe-mb$ unzip fritzing-parts-master.zip ~/Downloads
Archive:  fritzing-parts-master.zip
2631aa886c9f8d7a4a7d756f63fdd31c2232f6cc
caution: filename not matched:  /Users/gjwe-mb/Downloads

Would be gratefule if you would check the file.

Thanks,

George

**Comment by el-j** [comment]
hello George,
for me there is no problem with the downloaded zip file. maybe there was a connection problem during the download process? otherwise maybe your path is not correct? did you try another "unzip" tool?

what do you exactly enter in the commandline? isn't there  a "-d" missing?
`unzip file.zip -d destination_folder`
