### ISSUE TITLE
Format FZP Files

### ISSUE THREAD

**Issue by paulvollmer** [fritzing/fritzing-parts#134]
### Context:
cleanup fzp data and format to human readable style

### Problem or Idea:
at the moment some fzp files has some weird formatting and code folding will not work.

### Solution or Next step: 
format the xml code and overwrite the file. this will help all contributors reading fzp files.

- [x] implement formatter see: https://github.com/fritzing/fritzing-parts/compare/master...paulvollmer:feature-xml-formatter
- [ ] add script to travis-ci tests

i created a branch and commeted all formatted fzp files to it. see https://github.com/fritzing/fritzing-parts/compare/master...paulvollmer:feature-xml-format-fzps (NOTE: there is a merge conflict. only to see what will changed after running the formatter)

**Comment by KjellMorgenstern** [comment]
Partly fixed I think.

There are multiple tools in use to process fzp / xml files, some of them don't process xml files very human friendly.
This issue is outdated, since many of the fzp files have been changed, including some folding issues.

Most of our tooling is in python, some golang. I'd like to avoid adding js infrastructure requirements to the parts CI
