### ISSUE TITLE
Unique ID for 174917_DENSO-ECU-socket_48pin-040-070

### ISSUE THREAD

**Issue by wraybowling** [fritzing/fritzing-parts#182]
> The part '174917_DENSO-ECU-socket_48pin-040-070' at '/home/pi/Documents/Fritzing/parts/core/174917_DENSO-ECU-socket_48pin-040-070.fzp' does not have a unique module id 'DENSO 174917 ECU socket 48pin_c9a68151309697733439e70b6fbd83fd_1'.

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.

 - Which version of Fritzing have you been using?
  - On which operating system?
  - Which steps reproduce the problem?
  - Please add screenshots with error messages or rendering issues. Mark the problem with an image editor.
  - Attach your sketch file and/or custom part files to the bug report.
  - If the sketch uses custom parts, save the sketch as shareable (under the file menu).
  - Please use labels and text to provide additional information.
