### ISSUE TITLE
Relais maluska dil in V5 (only) mode can not be selected

### ISSUE THREAD

**Issue by ChaosLord76** [fritzing/fritzing-parts#194]
i just discovered, that when i select the maluska relais and switch to 5V mode, you can not select the device. where ever you click on it fritzing starts creating a wire connected to the common rail. When you switch to any other option (i.E. 5V - max 96 VDC) everything works fine.

Steve

**Comment by KjellMorgenstern** [comment]
Just reproduced the issue

![image](https://user-images.githubusercontent.com/6494025/60385458-8db29980-9a89-11e9-828e-086795260790.png)

Indeed, the part can not be moved on the breadboard.

**Comment by vanepp** [comment]
The problem here isn't the maluska relais part but the family. The family is relay which includes the Omron1 power relay which has a different pin out. Because the family is the same, Fritzing believes they are identical and tries to substitute one for the other, with the result you see (too few contacts in the Omron1 part causing the red background to indicate connector problems.) The solution would be to change the family name of the maluska relais part so it won't try and substitute a relay that doesn't have sufficient pins. In the longer term we need documentation and preferably automatic checking for the family to make sure all members have the correct number of pins.
